### ISSUE TITLE
Connection error: the parser IS not responding to the request (http://5.42.82.10:9117)

### ISSUE THREAD

**Issue by ancylow** [Jai707/WebOS-Piracy-Guide#2]
Not working for me. Follow all the steps but when I click on a movie or tv show and select torrents I receive a screen that says "It's empty here" and "Connection error: the parser is not responding to the request (http://5.42.82.10:9117)"

And I missing something? Thanks in advance

**Comment by zenkaigamer** [comment]
I also have same issue, couldn't get any results from any movie or tv show. Had exact same parser error.

**Comment by Jai707** [comment]
This is a known issue, I will update the guide with some alternative parser.

**Comment by Jai707** [comment]
Till then you can add your torrent by directly adding it to [server](http://torr.unknot.ru:8090) itself

**Comment by zenkaigamer** [comment]
> Till then you can add your torrent by directly adding it to [server](http://torr.unknot.ru:8090) itself
Can you give me an example? Can it be any video torrent online or only from torr.unknot.ru

**Comment by Jai707** [comment]
You can add any torrent/magnet link to the server using your PC/Mobile

**Comment by zenkaigamer** [comment]
I found your guide through google. So I know very little about the app. Could you please give me an example of what to do  Sorry for being a noob, I tried adding a magnet link to the torrserver and it didn't work

**Comment by Jai707** [comment]
> I found your guide through google. So I know very little about the app. Could you please give me an example of what to do Sorry for being a noob, I tried adding a magnet link to the torrserver and it didn't work

After adding magnet link did you reload torrent section in app?
To reload a certain section of app, click on section(torrents button for you) then you should see your added video

**Comment by zenkaigamer** [comment]
![Screenshot_20240401_094517_Chrome](https://github.com/Jai707/WebOS-Piracy-Guide/assets/165560041/d409567e-2e71-465d-9a12-4c5c967f12f1)
What am i doing wrong

**Comment by Jai707** [comment]
You have to add magnet link to the server by visiting [server](http://torr.unknot.ru:8090) not in the lampa app.
And keep the server url in main link.
Please read the guide carefully

**Comment by Jai707** [comment]
Just updated the parser's url.
Now everything should work just as intended.
